#!/usr/bin/env bash
# install nginx on a server
sudo apt update
sudo apt install nginx -y
sudo chown -R "$USER":"$USER" /var/www/html/*.html
echo "Hello World!" > /var/www/html/*.html
sudo nginx -s reload
