#!/usr/bin/env bash
# install nginx on a server
sudo apt update
sudo apt install nginx -y
echo  "Hello World!" |sudo tee  /var/www/html/index.html > /dev/null
sudo service nginx restart
sudo curl localhost
