#!/usr/bin/env bash
# install nginx on a new server and configure a redirect page
sudo apt update
sudo apt install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOT
server {
    listen 80;
    server_name _;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 http://www.idrisoft.tech;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOT
# restart nginx
sudo service nginx restart
sudo curl localhost
sudo curl localhost/redirect_me
