#!/usr/bin/env bash
# Installs HAProxy and configure it to send requests to two web applications using roundrobin

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0  -y
sudo apt-get install haproxy=2.0.\*  -y

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT

frontend www
	bind *:80
	default_backend allservers

backend allservers
	balance roundrobin
	server web1 54.157.170.157:80 check
	server web2 100.25.181.11:80 check
EOT

sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo systemctl start haproxy
sudo systemctl enable haproxy
sudo service haproxy restart
