#!/usr/bin/env bash
# write "I am alive" indefinitely to "/tmp/my_process"
file_name="/tmp/my_process"
touch "$file_name"  # create file if not exist

while true
do
	echo "I am alive!" >> "$file_name"
	sleep 2
done
