#!/usr/bin/env bash
# This script prints 1 to 20 with some superstitious numbers

num=1
while [ "$num" -le 20 ]
do
	echo "$num"
	case "$(( num++ ))" in 
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
done
