#!/usr/bin/env bash
# Print the name after the first "-" for each non-hidden filename in the current directory

visible_files=$(find ./ -maxdepth 1 | cut -s -d "-" -f2)

for file in $visible_files
do
	basename "$file"
done
