#!/usr/bin/env bash
#reset ufw to default
sudo ufw default deny incoming
sudo ufw default allow outgoing

# allow ssh, http and https
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# enable wfw
sudo ufw enable
