#!/usr/bin/env bash
# change hosts file

host_file="/etc/hosts"
temp_file="./host_temp"
addr="127.0.0.1\s+localhost|.*\s+facebook"
grep -vE "$addr" "$host_file" > "$temp_file"

echo "127.0.0.2	localhost" >> "$temp_file"
echo "8.8.8.8	facebook.com" >> "$temp_file"
cat "$temp_file" > "$host_file"
rm "$temp_file"
