#!/usr/bin/env bash
# configures nginx to run as nginx and serving on port 8080
sudo netstat -lnp | awk "/:8080/ {print $7}" | cut -d "/" -f2 | xargs pkill >&2 /dev/null | cat
sudo sed -i s/\ 80\ /\ 8080\ / /etc/nginx/sites-enabled/default
sudo apt-get install acl
sudo chown -R nginx:nginx /etc/nginx/ /var/log/nginx/ /usr/share/nginx/
sudo setfacl -m u:nginx:wrx /run
sudo chmod u+wr /etc/nginx/nginx.conf
su nginx -c "service nginx restart"
